# Write a function to compute 5/0 and use try/except to catch the exceptions.

In [0]:
def deviding(x,y):
  try:
    result=x/y
    print("your division result is",result)
  except ZeroDivisionError:
    print("your diving with zero choose another number")

In [0]:
deviding(3,0)

your diving with zero choose another number


# Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]


In [0]:
subject = ["Americans","Indians"]  
verb = ["Play", "watch"] 
obj = ["Baseball","cricket"]

In [0]:
for i in range(0,len(subject)):
  for j in range(0,len(verb)):
    for k in range(0,len(obj)):
      print(subject[i] +" " +verb[j] + " "+obj[k])

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


# Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.


In [0]:
import numpy as np
x = np.array([1, 2, 3, 5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [0]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [0]:
N=3
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [0]:
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [0]:
power = int(input("enter power"))

list = [1,2,3,4]
mat =[]
j=1
for i in list:
  for n in range((power-1),0 ,-1):
    mat.append(i**n)
  mat.append(j)
   
mat
  

enter power4


[1, 1, 1, 1, 8, 4, 2, 1, 27, 9, 3, 1, 64, 16, 4, 1]

In [0]:

def createMatrix(rowCount, colCount, dataList):
    mat = []
    for i in range(rowCount):
        rowList = []
        for j in range(colCount):
            # you need to increment through dataList here, like this:
            rowList.append(dataList[rowCount * i + j])
        mat.append(rowList)

    return mat

def main():
    mat
    mat1 = createMatrix(len(list),power,mat)
    print(mat1,end="\n")

main()

[[1, 1, 1, 1], [8, 4, 2, 1], [27, 9, 3, 1], [64, 16, 4, 1]]
